### ISSUE TITLE
Does this still work after the canary update?

### ISSUE THREAD

**Issue by SheepCommander** [AAGaming00/better-connections#3]
I can't tell

**Comment by AAGaming00** [comment]
Unsure, I don't use powercord anymore so I can't maintain this much, but if the extra connections show up in settings it should.On Jan 11, 2022 8:16 AM, SheepCommander ***@***.***> wrote:
I can't tell

**Comment by SheepCommander** [comment]
Ah I see. It does seem to show up in Plugins list but it does _not_ have a settings page

**Comment by AAGaming00** [comment]
Better connections does not have its own settings page, it just adds more options to the normal Connections setup page.On Jan 11, 2022 11:06 PM, SheepCommander ***@***.***> wrote:
Ah I see. It does seem to show up in Plugins list but it does not have a settings page

**Comment by SheepCommander** [comment]
ohhh okay aight
